### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by guilhermewaess** [niksmr/vue-masked-input#11]
Hi!
What I doing wrong, i did:
```
npm install vue-masked-input --save

import MaskedInput from 'vue-masked-input';

components:{
      MaskedInput
}
```

And then i'll receive the error:
Uncaught SyntaxError: Unexpected token import on import InputMask from 'inputmask-core' at MaskedInput.js

Any clue?

**Comment by luisfelipez** [comment]
Hi, fixed by importing `import MaskedInput from 'vue-masked-input/dist/component'`

Really works :+1:

**Comment by niksmr** [comment]
The issue looks rather unusual. 'Inputmask-core' should have been installed automatically as dependency when this component was installed, but, apparently, something went wrong. Try to install it explicitly: `npm i inputmask-core --save`. In any case, this problem does not apply to this component.

**Comment by latovicalmin** [comment]
package.json
`
"webpack": "^3.6.0",
"vue-masked-input": "^0.5.2"
`

Same issue here, I will remove this plugin
