### ISSUE TITLE
Trouble with runtime-only vue version

### ISSUE THREAD

**Issue by Ivan-Feofanov** [niksmr/vue-masked-input#12]
It falls because you use string template in component.

**Comment by shamego** [comment]
+1
cant compile with laravel-mix  in production mode (Uglifyjs throws error)
dev version works fine

<img width="815" alt="screen shot 2017-04-20 at 12 15 52" src="https://cloud.githubusercontent.com/assets/6264534/25223109/2872035e-25c3-11e7-8544-b88e2c9910d8.png">

**Comment by niksmr** [comment]
Fixed in 0.5.0
