### ISSUE TITLE
Can I do a Price format mask ?

### ISSUE THREAD

**Issue by murilolivorato** [niksmr/vue-masked-input#16]
Nice code my friend . Congratulations .
Can I make a price format mask ?

if I type this -

````
6756756075607665088
````
It will shows  -

````
67.567.560.756.076.650,88
````
Thanks

**Comment by murilolivorato** [comment]
?

**Comment by niksmr** [comment]
This component using [inputmask-core](https://github.com/insin/inputmask-core) as it's core, so this can not be implemented in this component. Once this feature is implemented there, it will work in this component too. So it's not part of the functionality of this particular component.
