### ISSUE TITLE
@blur event not working

### ISSUE THREAD

**Issue by shawjak3** [niksmr/vue-masked-input#17]
I can't get `@blur` event to trigger using your library.

Here is the input with your library:

`<masked-input type="text" class="form-control" name="birthday" v-model="form.birthday" placeholder="mm/dd/yyyy" mask="11/11/1111" @blur="ageFromBirthday" />`

Here is the same thing on a normal input:

`<input type="text" class="form-control" name="birthday" v-model="form.birthday" placeholder="mm/dd/yyyy" @blur="ageFromBirthday" />`

It just doesn't work with your library, is this a known issue? I am the latest version of your library as well.

**Comment by shawjak3** [comment]
Can anyone confirm this or tell me what I'm missing, I really need this for my project.

**Comment by niksmr** [comment]
Use `@blur.native`, [see why](https://vuejs.org/v2/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on-changed).
