### ISSUE TITLE
How to use with others directives?

### ISSUE THREAD

**Issue by MauriMelo** [niksmr/vue-masked-input#2]
Do you have any idea how to use with vee-validator?

`<masked-input type="text" v-model="birth_date" mask="11/11/1111" v-validate data-vv-rules="required" />`

**Comment by niksmr** [comment]
Tested your code, works fine for me. What do you mean by "how to use"?

**Comment by MauriMelo** [comment]
if you use {{ errors.has('birth_date') }} for example in your code, the Errors objects return undefined.

![vue devtools](https://cloud.githubusercontent.com/assets/5726711/22630957/1a56b5ce-ebeb-11e6-95a6-b03ccacc9b56.png)

In your code returns undefined? thanks for support ;)

**Comment by niksmr** [comment]
Well, the problem is on the vee-validate's side. Vee-validate gonna work like that _even if you use it with super basic custom input component_ like this one: 
```vue
<template>
  <input ref="input"
    :value="value"
    @input="$emit('input', $refs.input.value)"
  />
</template>

<script>
export default {
  name: 'MaskedInput',
  props: {
    value: {
      type: String
    }
  }

}
</script>
```
So that's not possible to fix inside the package.
