### ISSUE TITLE
custom regex support for mask option

### ISSUE THREAD

**Issue by shamego** [niksmr/vue-masked-input#20]
please, add custom regex support for mask option
smth like 
`<masked-input mask="a{10}" placeholder-char="*"/>`

instead of 

`<masked-input mask="aaaaaaaaaa" placeholder-char="*"/>`

**Comment by niksmr** [comment]
This component using [inputmask-core](https://github.com/insin/inputmask-core) as it's core, so this can not be implemented in this component. Once this feature is implemented there, it will work in this component too. Unfortunately there is [issue](https://github.com/insin/inputmask-core/issues/1) with this request opened for a long time.
