### ISSUE TITLE
Unexpected character '`'  problem

### ISSUE THREAD

**Issue by mesutgok** [niksmr/vue-masked-input#21]
Hi, 

thank u first, npm run build problem

> ERROR in static/js/vendor.45cf410bef1d1ee48a7d.js from UglifyJs
Unexpected character '`' [./~/vue-masked-input/src/MaskedInput.js:7,0][static/js/vendor.45cf410bef1d1ee48a7d.js:61918,12]

what is the problem ? how to fix ? Ie not working app

**Comment by AlexQuidditch** [comment]
I have same problem

**Comment by fabriciobeltran** [comment]
same here!

**Comment by maximus1010101** [comment]
What version can we use now?

**Comment by zaguini** [comment]
+1

**Comment by ArroWsGM** [comment]
[Fork: Solving unexpected character '`' problem in webpack's uglifyjs](https://github.com/ArroWsGM/vue-masked-input)

**Comment by niksmr** [comment]
Fixed in 0.5.0, please update

**Comment by victorboissiere** [comment]
@niksmr do you remember how did you fix it ? I have the same issue on another project and I do know how to resolve it. I would like to make a pull request but I have no idea was is causing the issue :/

**Comment by niksmr** [comment]
@victorboissiere do you use 0.5.0^ version? The reason for the issue was the use of ES6-template literals. Starting with version 0.5.0, they are no longer there.

**Comment by victorboissiere** [comment]
I was talking about the same error happening on a completely different package. I guess you just removed the ES6-template literals to fix it! Thank you and sorry to ask here I was so desperate :/
