### ISSUE TITLE
Laravel Mix Webpack Production Compilation Problem

### ISSUE THREAD

**Issue by plexus77** [niksmr/vue-masked-input#5]
I found an issue with ff-polyfill.js when trying to compile my app for production.

It was throwing an error and failing...

SyntaxError: Unexpected token: punc ()) [./~/vue-masked-input/src/ff-polyfill.js:2,0]

I needed to change

`export` default () => {

to

`export` default function() {

then everything worked fine :)

**Comment by gabrielboliveira** [comment]
Agree with this issue. You don't need to use arrow functions on export. Changing to function fix the build.

**Comment by niksmr** [comment]
Fixed in 0.4.1
