### ISSUE TITLE
Optional number

### ISSUE THREAD

**Issue by renanpro03** [niksmr/vue-masked-input#6]
Hi, in Brazil we have mobile phone like this (xx) x xxxx-xxxx  and normal phone like this (xx) xxxx-xxxx

So, using jquery mask I was able do do something like this:
$(".phone").mask("(99) 9999-9999?9");

The last number is optional using the question mark, is there a way to do that unsing your component?
Thanks

**Comment by niksmr** [comment]
It is not gonna work for now that way, but maybe I will implement it in the future. The best thing you can do now is add the radio button or something like that and change the mask if necessary.

**Comment by kl3sk** [comment]
Any chances to have this feature ?
