### ISSUE TITLE
Compatibility with Vuejs 3

### ISSUE THREAD

**Issue by ivandamyanov** [niksmr/vue-masked-input#62]
I have a vue-cli project and I cannot even setup the plugin to work, is it compatible? For instance, in vuejs 3 you usually have to import the component before you could do <input-mask> but you lack this in the setup guide. I tried it and it still didn't work.

**Comment by brunbs** [comment]
Did you make it work? I'm trying but I can't make it work

**Comment by ivandamyanov** [comment]
Unfortunately not. I think I gave up on the masking idea and that's why I closed this.
