### ISSUE TITLE
min/max Values

### ISSUE THREAD

**Issue by kayyyy** [niksmr/vue-masked-input#7]
Hi,

great Component so far, very slim 👍 

But is there a Way to allow min/max Values? For Example i want a mask where the User can type the Amount of Money.

e.g

```
<masked-input class="form-control"
                           mask="11 , 11"
                           placeholder="0,00"
                           @input="form.amount = arguments[1]"
/>
```

Now the Problem is, the User can only type `10` to `99`. But what if he wants to write 1000. This is now gonna work. So is there a Way to allow min/max Values so the User can type 10 or 1000?

**Comment by niksmr** [comment]
This repo is in fact only a bridge from inputmask core to vue component. There is no way right now to realize that logic in inputmask core, so that's not possible to allow min/max values right now.
